# SHAPE

In [5]:
import numpy as np
var = np.array([[1,2,3,4], [1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


# multidimension array

In [6]:
var = np.array([1,2,3,4], ndmin=5 )
print(var)


[[[[[1 2 3 4]]]]]


In [7]:
print(var.ndim)

5


In [8]:
print(var.shape)

(1, 1, 1, 1, 4)


# reshape (conver array to multi or mulit to array)

In [20]:
var2= np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)

x= var2.reshape(3,2)
print(x)

print(x.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


In [32]:
import numpy as np
var3= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)

x= var3.reshape(2,3,2)
print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


# move 3d to 1d

In [39]:
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var)

x= var.reshape(2,3,2)
print(x)
print(x.ndim)

#convert

one= x.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
