# iteration

In [4]:
import numpy as np
var= np.array([1,2,3,4,5,6])
print(var)
print()

for i in var:
    print(i)

[1 2 3 4 5 6]

1
2
3
4
5
6


# 2d array

In [5]:
var1= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(var1)

for j in var1:
    print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
[ 6  7  8  9 10]


In [9]:
# itteration k andar iteraiton

import numpy as np
var= np.array([[1,2,3,4,5],[6,7,8,9,10]])

for k in var:
    print(k)
    for l in k:
        print(l)

[1 2 3 4 5]
1
2
3
4
5
[ 6  7  8  9 10]
6
7
8
9
10


In [11]:
# for 3-D array


In [12]:
import numpy as np
var3= np.array([[[1,2,3,4],[4,5,6,7],[5,6,7,8]]])
print(var3.ndim)

3


In [13]:
for i in var3:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
4
5
6
7
5
6
7
8


In [14]:
var3= np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)

print(var3)

for i in np.nditer(var3):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
3
[[[9 8 7 6]
  [1 2 3 4]]]
9
8
7
6
1
2
3
4


In [15]:
var3= np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)

print(var3)

for i in np.nditer(var3):
    print(i, type(i))

[[[9 8 7 6]
  [1 2 3 4]]]
3
[[[9 8 7 6]
  [1 2 3 4]]]
9 <class 'numpy.ndarray'>
8 <class 'numpy.ndarray'>
7 <class 'numpy.ndarray'>
6 <class 'numpy.ndarray'>
1 <class 'numpy.ndarray'>
2 <class 'numpy.ndarray'>
3 <class 'numpy.ndarray'>
4 <class 'numpy.ndarray'>


In [16]:
# data type change


In [21]:
import numpy as np
var3= np.array([[[9,8,7,6],[1,2,3,4]]])

print(var3)
print()

# for i in np.nditer(var3, flags = ['buffered'], op_dtypes= ["s"]):
#     print(i)

for i in np.nditer(var3,flags= ['buffered'], op_dtypes= ["S"]):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]

b'9'
b'8'
b'7'
b'6'
b'1'
b'2'
b'3'
b'4'


In [25]:
import numpy as np
a= np.array([[[1,2,3,4], [5,6,7,8]]])
print(a)

for i in np.ndenumerate(a):
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
