# shuffle

In [2]:
import numpy as np

var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[4 2 5 3 1]


# unique function

In [6]:
a= np.array([1,2,3,4,5,6,7,2,4,5,2,1])
b= np.unique(a,return_index= True,return_counts=True)
print(b)

print()
print()

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 6], dtype=int64), array([2, 3, 1, 2, 2, 1, 1], dtype=int64))




# resize function

In [7]:
c= np.array([1,2,3,4,5,6,7])
d= np.resize(a,(2,3))
print(d)

[[1 2 3]
 [4 5 6]]


# flatten function

In [9]:
e= np.array([[1,2,3,4], [5,6,7,8]])
print(e.flatten())

[1 2 3 4 5 6 7 8]


# ravel

In [11]:
f= np.array([[1,2,3,4],[5,6,7,8]])
print("ravel:", np.ravel(f))

ravel: [1 2 3 4 5 6 7 8]
