# DATA TYPE 

In [1]:
import numpy as np 
var = np.array([1,2,3,4,])
print("data type: ", var.dtype)

data type:  int32


In [2]:
import numpy as np
var = np.array(['a','b','c'])
print("data type:", var.dtype)

data type: <U1


In [3]:
import numpy as np
var= np.array([1.4, 4,5,4,2,5])
print('data type:', var.dtype)

data type: float64


In [4]:
import numpy as np
var = np.array(['a','b','c',1,3,4,5.5, 88])
print('data type:', var.dtype)

data type: <U32


# type casting

In [6]:
import numpy as np
x= np.array([1,2,3,4], dtype = np.int8)
print('data type:', x.dtype)
print(x)

data type: int8
[1 2 3 4]


# convert in float

In [7]:
import numpy as np
x= np.array([1,2,3,4], dtype = 'f')
print('data type:', x.dtype)
print(x)
  

data type: float32
[1. 2. 3. 4.]


In [8]:
import numpy as np
x= np.array([1,2,3,4])
new = np.float32(x)
new_one = np.int_(new)
print('data type:', x.dtype)
print(new)
print(new_one)
print(x)

data type: int32
[1. 2. 3. 4.]
[1 2 3 4]
[1 2 3 4]


In [10]:


x= np. array([1,2,3,4])
new_1 =  x.astype(float)
print(type(x),x)
print(new_1)

<class 'numpy.ndarray'> [1 2 3 4]
[1. 2. 3. 4.]
