# search

In [ ]:
import numpy as np
var= np.array([1,2,3,4,5,6,7,8,9,4,5,6,7])

x= np.where(var==4)
print(x)

In [4]:
import numpy as np
a= np.array([1,2,3,4,5,6,7,8])
y=np.where(var%2==0)
print(y)

(array([ 1,  3,  5,  7,  9, 11], dtype=int64),)


# search sort array

In [13]:
import numpy as np
x= np.array([1,2,3,4,5,6,7,8, 11,4,5,9,])
y= np.searchsorted(x,9)
print(y)

11


In [14]:
import numpy as np
a= np.array([1,2,3,4,5,6,15])
b=np.searchsorted(a,10, side= 'right')
print(b)

6


In [15]:
import numpy as np
a= np.array([1,2,3,4,5,6,15])
b=np.searchsorted(a,10, side= 'left')
print(b)

6


In [17]:
import numpy as np
c= np.array([1,2,3,4,5,6,7])
d= np.searchsorted(c,[1,6,7,8])
print(d)

[0 5 6 7]


In [18]:
import numpy as np
c=np.array([1,2,3,4,8,9])
k=np.searchsorted(c,[5,6,7])
print(k)

[4 4 4]


# sort

In [19]:
import numpy as np

a= np.array([6,4,7,3,8,9,1,10,15,12,13])
print(np.sort(a))

[ 1  3  4  6  7  8  9 10 12 13 15]


In [20]:
b= np.array(['a','s','d','f'])
print(np.sort(b))

['a' 'd' 'f' 's']


# 2D array

In [21]:
c= np.array([[4,2,3],[1,12,11],[22,52,6]])
print(np.sort(c))

[[ 2  3  4]
 [ 1 11 12]
 [ 6 22 52]]


# filter array

In [23]:
d= np.array(['a','s','d','f'])
f=[True,False,False,True]
a=d[f]
print(a)
print(type(a))

['a' 'f']
<class 'numpy.ndarray'>
