# random functtion


# rand()

In [1]:
# 1D ARRAR

import numpy as np
var= np.random.rand(4)
print(var)

[0.19897059 0.9143034  0.58849681 0.09706566]


In [2]:
# 3D ARRAY 

import numpy as np
var2= np.random.rand(3,5)
print(var2)

[[0.02275637 0.75964169 0.7337768  0.3362031  0.50316643]
 [0.19874784 0.59919056 0.21704268 0.46878847 0.82870091]
 [0.77927733 0.50823286 0.7352135  0.61583879 0.94872597]]


# randn()


In [3]:
import numpy as np
var = np.random.randn(5)
print(var)

[ 0.87247977 -0.68591832  0.2015303  -0.16299813 -0.69748025]


# ranf()

In [5]:
import numpy as np
var = np.random.ranf(4)
print(var)

[0.84213913 0.48181358 0.37966341 0.57333959]


# randint()

In [7]:
import numpy as np
var = np.random.randint(5,20,5)
print(var)

[15 19 19 14 19]
