In [4]:
import numpy as np
var1= np.array([1,2,3,4])
print(var1.shape)

var2= np.array([1,2,3,6])
print(var2.shape)

var= var1+var2
print(var)

(4,)
(4,)
[ 2  4  6 10]


In [9]:
import numpy as np
var1= np.array([1,2,3])
print(var1)

var2= np.array([[1],[2],[3]])
print(var2)
print(var2.ndim)
print(var2.shape)


print(var1+var2)

[1 2 3]
[[1]
 [2]
 [3]]
2
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [13]:
x= np.array([[1],[2]])
print(x.shape)

y=np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]
