# how to create array in numpy



In [2]:
import numpy as np

x=[1,2,3,4]
y=np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
l=[]

for i in range(1,5):
    int_l = int(input('enter:'))
    l.append(int_l)
print(np.array(l))

enter:23
enter:2324
enter:3423
enter:434324
[    23   2324   3423 434324]


# types of array

In [5]:
# 1D-[1,33,45,34]
# 2D-[[1,3,4,54,33]]
# 3D-[[[2,3,5,65,6,]]]


In [6]:
x=[1,2,3,4,5]
y=np.array(x)
print(y)


#dimension check
print(y.ndim)

[1 2 3 4 5]
1


In [7]:
#2 dimension arrya

x=[[1,2,3,4,5]]
y=np.array(x)
print(y)
print(y.ndim)

[[1 2 3 4 5]]
2


In [10]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
print(ar2.ndim)
print(ar2)

2
[[1 2 3 4]
 [5 6 7 8]]


In [11]:
ar2 = np.array([[1,2,3,4],[5,6,7,8,9]])
print(ar2.ndim)
print(ar2)

1
[list([1, 2, 3, 4]) list([5, 6, 7, 8, 9])]


C:\Users\Santosh Dhavan\AppData\Local\Temp\ipykernel_14960\1088413431.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2 = np.array([[1,2,3,4],[5,6,7,8,9]])


In [12]:
ar2 = np.array([[1,2,3,4],[5,6,7]])
print(ar2.ndim)
print(ar2)

1
[list([1, 2, 3, 4]) list([5, 6, 7])]


C:\Users\Santosh Dhavan\AppData\Local\Temp\ipykernel_14960\976730200.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2 = np.array([[1,2,3,4],[5,6,7]])


In [13]:
# 3D

ar3= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3.ndim)

3


In [14]:
# ND ARRAY

arn= np.array([1,2,3,4],ndmin=10)
print(arn.ndim)

10


In [17]:
# ND ARRAY

arn= np.array([1,2,3,4],ndmin=20)
print(arn.ndim)

20
