# arithmetic operation

In [1]:
import numpy as np

var = np.array([1,2,3,4])
varadd= var+3
print(varadd)

[4 5 6 7]


In [2]:
var = [1,2,3,4]
var1= var+2
print(var1)

TypeError: can only concatenate list (not "int") to list

In [14]:
import numpy as np
var1= np.array([1,2,3,4,5])
var2= np.array([5,6,7,3,4])

varadd= var1+var2
#varadd= np.add(var1,var2)------>   function
print(varadd)

[ 6  8 10  7  9]


# subtraction

In [4]:
import numpy as np
var1= np.array([1,2,3,4,5])
var2=np.array([4,5,6,3,4])
varmin= var1-var2
print(varmin)

[-3 -3 -3  1  1]


In [7]:
import numpy as np
var1= np.array([1,2,3,4,5])
var2= np.array([5,6,7,7,4])
varmodulo= var2%var1
print(varmodulo)

[0 0 1 3 4]


In [8]:
import numpy as np
var1= np.array([1,2,3,4,5])
var2= np.array([5,6,7,7,4])
varmodulo= var2/var1
print(varmodulo)

[5.         3.         2.33333333 1.75       0.8       ]


In [12]:
import numpy as np
var1= np.array([1,2,3,4,5])
var2= np.array([5,6,7,7,4])
varmodulo= var2//var1
print(varmodulo)

[5 3 2 1 0]


# 2D ARRAY

In [16]:
import numpy as np
var21= np.array([[1,2,3,4],[1,2,3,4]])
var22= np.array([[1,2,3,4,], [6,7,8,9]])

#|varadd = np.add(var21,var22)
varadd= var21+var22
print(varadd)


[[ 2  4  6  8]
 [ 7  9 11 13]]
