# insert

In [8]:
import numpy as np
var= np.array([1,2,3,4])
print(var)

a= np.insert(var,(2,4),40)
print(a)

[1 2 3 4]
[ 1  2 40  3  4 40]


## 2D


In [9]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
b= np.insert(a,2,7,axis=1)
print(b)

[[1 2 7 3]
 [4 5 7 6]]


# append function

In [12]:
import numpy as np

c= np.array([1,2,3,4,5])
d= np.append(c,6)
print(d)

[1 2 3 4 5 6]


# delete

In [16]:
import numpy as np

a= np.array([1,2,3,4,5])
print(a)

d= np.delete(a,3)
print(d)




[1 2 3 4 5]
[1 2 3 5]
