# indexing


In [2]:
import numpy as np

var= np.array([1,2,3,4,5])
#indexing start with o

print(var[1])
print(var[-1])

2
5


In [9]:
# 2d aray
var2= np.array([[1,2,3,4,5],[7,5,8,9,11]])
print(var2.shape)
print(var2.ndim)



print(var2[0,1])

(2, 5)
2
2


# 3D array

In [19]:
var3= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(var3.shape)
print(var3.ndim)
# print(var3[1,1,0])
print(var3)
print(var3[0,1,1])
print(var3[0,0,0])

(1, 3, 4)
3
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
6
1


# slicing

In [29]:
import numpy as np

var = np.array([1,2,3,4,5,6,7])
print(var)
print()

print(var[2:6])


print()
print("2 to end: ", var[1:])
print("start to end:", var[:])
print("start to 5: ", var[:6])

print()
print("jum :", var[0::2])

[1 2 3 4 5 6 7]

[3 4 5 6]

2 to end:  [2 3 4 5 6 7]
start to end: [1 2 3 4 5 6 7]
start to 5:  [1 2 3 4 5 6]

jum : [1 3 5 7]


In [32]:
var1= np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1.ndim)
print(var1)
print("8to 5:", var1[1,1:])

2
[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
8to 5: [8 7 6 5]
