# array filled by zero 
import numpy as np

# 1 dim. array

ar_zero= np.zeros(4)

# 3 dim. array

ar_zero1= np.zeros((3,4))
print(ar_zero)
print('dono k bich mai space k liyae hai')
print(ar_zero1)



# array filled by one


In [8]:
# array for 1

import numpy as np
ar_one= np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


# array filled by empty

In [9]:
ar_emp=np.empty(4)
print(ar_emp)

[1. 1. 1. 1.]


# range array

In [10]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


# diagonal

In [13]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
ar_dia = np.eye(5,6)
print(ar_dia)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


# linspace

In [21]:
ar_lin = np.linspace(0,10, num =12)
print(ar_lin)

[ 0.          0.90909091  1.81818182  2.72727273  3.63636364  4.54545455
  5.45454545  6.36363636  7.27272727  8.18181818  9.09090909 10.        ]
