# join array

In [2]:
import numpy as np
var=np.array([1,2,3,4])
var1=np.array([8,6,7,5])
ar=np.concatenate(var,var1)
print(ar)

TypeError: only integer scalar arrays can be converted to a scalar index

In [3]:
import numpy as np
var=np.array([1,2,3,4])
var1=np.array([8,6,7,5])
ar=np.concatenate(var,var1)
print(ar)

TypeError: only integer scalar arrays can be converted to a scalar index

In [6]:
import numpy as np
var=np.array([1,2,3,4])
var1= np.array([9,8,7,6])
ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [7]:
import numpy as np
var=np.array([1,2,3,4])
var1= np.array([9,8,7,6, 3,2,1])
ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6 3 2 1]


# for 2D array

In [10]:
vr= np.array([[1,2],[3,4]])
vr1=np.array([[5,6],[7,8]])
ary= np.concatenate((vr,vr1), axis=1)
print(ary)

[[1 2 5 6]
 [3 4 7 8]]
